Ckey binder token generator to profile
ChaoticOnyx/OnyxForum pull request #70
Opened 2022-07-10 13:51 UTC by Zert0X

Генератор токенов для привязки сикеев теперь есть на страничке профиля:
![изображение](https://user-images.githubusercontent.com/42303535/178147713-e92aeb9f-1ae6-4c51-9afa-9f9de0bb4045.png)

При нажатии, выводит информацию

2022-07-10 13:53 UTC, Doster-d requested changes
Друг, f строка и никакой ебли с форматом.

2022-07-10 13:53 UTC, Doster-d commented on flaskbb/user/views.py
> +        flash("Ваш токен {}. Чтобы выполнить привязку BYOND аккаунта, введите его, с помощью консольной команды `.chaotic-token` на одном из наших серверов.".format(new_token.token))
```suggestion
        flash(f"Ваш токен {new_token.token}. Чтобы выполнить привязку BYOND аккаунта, введите его, с помощью консольной команды `.chaotic-token` на одном из наших серверов.")
```

2022-07-10 13:54 UTC, Zert0X commented on flaskbb/user/views.py
> +        flash("Ваш токен {}. Чтобы выполнить привязку BYOND аккаунта, введите его, с помощью консольной команды `.chaotic-token` на одном из наших серверов.".format(new_token.token))
Похуй?

2022-07-10 13:54 UTC, Doster-d commented on flaskbb/user/views.py
> +        flash("Ваш токен {}. Чтобы выполнить привязку BYOND аккаунта, введите его, с помощью консольной команды `.chaotic-token` на одном из наших серверов.".format(new_token.token))
Не красиво, го f строку

2022-07-10 13:56 UTC, Zert0X commented on flaskbb/user/views.py
> +        flash("Ваш токен {}. Чтобы выполнить привязку BYOND аккаунта, введите его, с помощью консольной команды `.chaotic-token` на одном из наших серверов.".format(new_token.token))
не в код стайле форума
![изображение](https://user-images.githubusercontent.com/42303535/178147894-235dbb8f-456e-460a-b110-7c7082851689.png)

2022-07-11 14:04 UTC, Doster-d commented on flaskbb/user/views.py
> +        routes=["/user<userid>/generate-token"],
Так это профиль игрока, логично что все что связано с игроком будет проходить через профиль

2022-07-11 19:03 UTC, merged