Subforums
ChaoticOnyx/OnyxForum pull request #73
Opened 2022-07-15 07:52 UTC by Zert0X

![изображение](https://user-images.githubusercontent.com/42303535/179178188-a327220c-2203-4220-b821-6b7211af7fd0.png)

2022-07-25 20:58 UTC, No-Tips commented on flaskbb/templates/forum/forum.html
> +    {% if forum.subforums.all() != [] %}
Просто 
```suggestion
    {% if forum.subforums.all() %}
```

2022-07-26 09:34 UTC, No-Tips commented on flaskbb/management/forms.py
> +            if self.subforum_parent_id == None:
```suggestion
            elif not self.subforum_parent_id:
```
В питоне есть конструкция elif, вместо ебучего нестед else: if
Ну если сабфорум_парент_айди не может быть 0 или нуллом - можно и if not юзать

2022-07-26 09:36 UTC, No-Tips commented on flaskbb/forum/models.py
> +                filter(Forum.groups.any(Group.id == guest_group.id), Forum.subforum_parent_id == None).\
Тут кстати тоже мб можно обойтись без == None , написав none, но МОЖЕТ быть фильтры так не работают.

2022-08-02 16:50 UTC, Epicus7 requested changes

2022-08-02 16:50 UTC, Epicus7 commented on flaskbb/management/forms.py
> +                raise ValidationError(_("You need to specify parent forum"))
Еще бы проверить subforum_parent_id на существование, наверное

2022-08-02 16:50 UTC, Epicus7 commented on flaskbb/templates/macros.html
> +{%- macro render_forum_managment(forum, render_subforums) -%}
Еще я не вижу чтобы render_forum_managment вызывался со вторым параметром False. Можно от него избавиться

2022-08-02 16:50 UTC, Epicus7 commented on flaskbb/templates/macros.html
> +                    <a class="btn btn-sm btn-primary" href="{{ url_for('management.edit_forum', forum_id = forum.id, is_subforum=1, parent_id=forum.subforum_parent_id) }}">
И тогда от этого условия тут можно будет избавиться

2022-08-02 16:50 UTC, Epicus7 commented on flaskbb/management/views.py
> +                form.is_subforum.data = True
И ниже с parent_id тоже самое

2022-08-02 16:50 UTC, Epicus7 commented on flaskbb/themes/onyx/src/js/forum_form.js
> +    console.log($(".setting-form #category option:selected").val())
Дебажный вывод лишний, наверное?

2022-08-02 16:50 UTC, Epicus7 commented on flaskbb/utils/requirements.py
> +        return bool(forum_groups & user_groups)
`bool(forum_groups & user_groups)` дублируется, не хорошо. Лучше так:

```suggestion
    if forum.subforum_parent_id and not can_user_access_forum(user, Forum.query.filter_by(id=forum.subforum_parent_id).first():
        return False
    return bool(forum_groups & user_groups)
```

2022-08-02 16:56 UTC, Zert0X commented on flaskbb/templates/macros.html
> +                <a class="btn btn-sm btn-success" href="{{ url_for('management.add_forum', category_id=forum.category_id, is_subforum=1, parent_id=forum.id) }}">
Була не существует, ну или я рак и у меня не получилось

2022-08-02 16:57 UTC, Zert0X commented on flaskbb/templates/management/forums.html
> +                            {% if not forum.subforum_parent_id %}
Потому что айди категории выставляется по родительскому форуму, на тот случай если мы захотим удалить подфорумы как таковые, все записи в БД будут валидны и не потребуют излишних вмешательств

2022-08-02 17:00 UTC, Zert0X commented on flaskbb/forum/models.py
> +                filter(Forum.groups.any(Group.id.in_(user_groups)), Forum.subforum_parent_id == None).\
Уже описал выше

2022-08-02 17:04 UTC, Zert0X commented on flaskbb/management/forms.py
> +        allow_blank=False,
Сделано в связи с тем что если поля обязательно, то даже при выключенной галочке is_subforum форма будет требовать выставить род. форум

2022-08-02 17:05 UTC, Zert0X commented on flaskbb/management/forms.py
> +                raise ValidationError(_("You need to specify parent forum"))
А смысл если он энивей существует, ты не можешь поле выбора оставить пустым вроде как?

2022-08-02 17:11 UTC, Zert0X commented on flaskbb/management/views.py
> +        parent_id = request.args.get("parent_id", 0, type=int)
Они добавляются от кнопки Add Subforum у форума

2022-08-02 17:22 UTC, Zert0X commented on flaskbb/management/views.py
> +        parent_id = request.args.get("parent_id", 0, type=int)
Посмотри на пару строчек ниже, там мы выставляем на место категорию, видимо при рендере формы сбиваются все значения, поэтому это и есть передача формы пользователю так как он настроил

2022-08-02 17:49 UTC, Epicus7 commented on flaskbb/management/forms.py
> +        allow_blank=False,
Так ты же запретил наоборот пустое поле. Разве не должно быть True?

2022-08-02 17:50 UTC, Epicus7 commented on flaskbb/management/forms.py
> +                raise ValidationError(_("You need to specify parent forum"))
Я могу через режим разработчика любую фигню тебе сюда отправить и оно сохранится в БД, сломав нам форум

2022-08-02 17:50 UTC, Epicus7 commented on flaskbb/management/forms.py
> +                raise ValidationError(_("You need to specify parent forum"))
На стороне бекенда надо проверять вообще все, потому что пользователь может мимо твоих форм отправить нам что угодно сырым Post-запросом

2022-08-02 17:58 UTC, Epicus7 commented on flaskbb/management/views.py
> +        parent_id = request.args.get("parent_id", 0, type=int)
> Они добавляются от кнопки Add Subforum у форума

Эта кнопка ведет в get, а не в post.

> видимо при рендере формы сбиваются все значения

Не должно ничего сбиваться, само все должно работать.

2022-08-02 17:59 UTC, Epicus7 commented on flaskbb/templates/management/forums.html
> +                            {% if not forum.subforum_parent_id %}
Ок

2022-08-02 18:00 UTC, Epicus7 commented on flaskbb/forum/models.py
> +                filter(Forum.groups.any(Group.id.in_(user_groups)), Forum.subforum_parent_id == None).\
Ок

2022-08-02 18:18 UTC, Epicus7 commented on flaskbb/management/forms.py
> +        allow_blank=False,
Ладно, ок

2022-08-03 08:45 UTC, Zert0X commented on flaskbb/management/forms.py
> +                raise ValidationError(_("You need to specify parent forum"))
![изображение](https://user-images.githubusercontent.com/42303535/182565444-eb453047-6d76-47ae-9b94-9c21e3d58ee7.png)
![изображение](https://user-images.githubusercontent.com/42303535/182565479-bcf6325d-daea-4436-be8e-24af6d2e6fdb.png)

2022-08-03 08:46 UTC, Zert0X commented on flaskbb/management/forms.py
> +                raise ValidationError(_("You need to specify parent forum"))
сырым пост запросом ты и сейчас можешь насрать в поле категории или в модераторов

2022-08-03 08:48 UTC, Zert0X commented on flaskbb/management/forms.py
> +                raise ValidationError(_("You need to specify parent forum"))
И да если в самом поле что-то не то выставлено значение идёт в None, поэтому в целом проверить существует форум или нет в самом валидаторе не получится, это надо делать уже в методе save у формы

2022-08-03 08:50 UTC, Zert0X commented on flaskbb/management/views.py
> +        parent_id = request.args.get("parent_id", 0, type=int)
![изображение](https://user-images.githubusercontent.com/42303535/182566145-3bb0d7c4-7f34-4ad2-9081-92033860767c.png)

Вот собственно говоря, если юзер лох и насрал, то ему устанавливается самый первый возможный форум в парент id, а мы же хотим чтобы даже в случае если юзер лох то форма ему подставляла сама парент айди повторно

2022-08-03 08:53 UTC, Zert0X commented on flaskbb/management/views.py
> +                form.is_subforum.data = True
аналогично и в эдите

2022-08-03 10:51 UTC, Epicus7 commented on flaskbb/management/forms.py
> +                raise ValidationError(_("You need to specify parent forum"))
Ок

2022-08-03 10:52 UTC, Epicus7 commented on flaskbb/management/views.py
> +        parent_id = request.args.get("parent_id", 0, type=int)
А, ок

2022-08-03 10:53 UTC, Epicus7 commented on flaskbb/management/views.py
> +                form.is_subforum.data = True
Ок

2022-08-03 10:57 UTC, Epicus7 requested changes

2022-08-03 10:57 UTC, Epicus7 commented on flaskbb/management/forms.py
> +        if not data['parent_id'] == None:
```suggestion
        if data['parent_id']:
```

2022-08-03 10:57 UTC, Epicus7 commented on flaskbb/management/forms.py
> +        if not data['parent_id'] == None:
```suggestion
        if data['parent_id']:
```

2022-08-03 10:57 UTC, Epicus7 commented on flaskbb/management/views.py
> +        if not forum.parent_id == None:
```suggestion
        if forum.parent_id:
```

2022-08-03 10:57 UTC, Epicus7 commented on flaskbb/management/views.py
> +        if not forum.parent_id == None:
```suggestion
        if forum.parent_id:
```

2022-08-03 10:57 UTC, Epicus7 commented on flaskbb/management/views.py
> +            form.parent_id.data = parent
```suggestion
        if parent_id:
            form.is_subforum.data = True
            parent = Forum.query.filter_by(id=parent_id).first_or_404()
            form.parent_id.data = parent
```

2022-08-03 10:58 UTC, Epicus7 commented on flaskbb/templates/macros.html
> +{%- macro render_forum_managment(forum, render_subforums) -%}
> И какие-то эти макросы слишком уж специфичные, по сравнению с остальными макросами. Лучше в отдельный файл вынести это дело, чтобы мешать их с макросами более широкого спектра использования

Вот это не исправил

2022-08-03 10:59 UTC, Zert0X commented on flaskbb/templates/macros.html
> +{%- macro render_forum_managment(forum, render_subforums) -%}
А есть смысл дробить файл с макросами? Макросы лежат в файлике macros.html

2022-08-03 11:28 UTC, Epicus7 approved these changes

2022-08-03 11:29 UTC, Epicus7 commented on flaskbb/templates/macros.html
> +{%- macro render_forum_managment(forum, render_subforums) -%}
Перенесли в отдельный файл

2022-08-03 11:31 UTC, merged