Added abbility to get admins wia curl <> | jq
ChaoticOnyx/OnyxForum pull request #74
Opened 2022-07-26 11:33 UTC by Zert0X

close #12 
![изображение](https://user-images.githubusercontent.com/42303535/180996174-ea63d5be-4394-43cf-9e0d-d1b6b4e5efef.png)

2022-07-26 12:35 UTC, No-Tips commented on modules/hub/hub/views.py
> +        result = {rank:[admin.ckey for admin in admins if admin.rank == rank] for rank in [admin.rank for admin in admins]}
Для чего тут проверка if admin.rank == rank, я не могу вдуплить.

2022-07-26 12:35 UTC, No-Tips commented on modules/hub/hub/views.py
> +        return result
Нюлайн или пидор.
```suggestion
        return result
        
```

2022-07-26 12:35 UTC, No-Tips commented on modules/hub/hub/gameserver_models.py
> +    __tablename__ = 'erro_admin'
Тейблнейм мб перенести в ерро админ?

2022-07-26 12:38 UTC, No-Tips commented
И оно будет работать вообще с ботом доока?

2022-07-26 12:40 UTC, Zert0X commented on modules/hub/hub/gameserver_models.py
> +    __tablename__ = 'erro_admin'
Нет, ибо это поле db_onyx.Model, которое мы наследуем сюда

2022-07-26 12:40 UTC, Zert0X commented on modules/hub/hub/views.py
> +        result = {rank:[admin.ckey for admin in admins if admin.rank == rank] for rank in [admin.rank for admin in admins]}
ибо мы печатаем админов для текущего ранка

2022-07-26 12:42 UTC, Zert0X commented
> И оно будет работать вообще с ботом доока?

А какая разница, бот свою команду выполняет ему абы был доступ на страничку и правильный формат.
Оба требования соблюдены

2022-07-27 07:33 UTC, No-Tips commented on modules/hub/hub/templates/hub/server/admins.html
> +{% endblock %}
Нюлайн

2022-07-27 07:36 UTC, No-Tips commented on modules/hub/hub/views.py
> +        print(is_json)
Кажется, ты забыл убрать принт

2022-07-27 07:38 UTC, No-Tips requested changes

2022-07-27 07:38 UTC, No-Tips commented on modules/hub/hub/views.py
> +        is_json = request.endpoint
Вообще какой-то костыл. Этот гет вызывается на каждой странице, но ничего не делает на всех, кроме эндпоинта с жсом?

2022-07-27 08:05 UTC, No-Tips commented on modules/hub/hub/views.py
> +        is_json = request.endpoint
А я тупой, в каждом AdminsView.

2022-08-02 15:50 UTC, Epicus7 requested changes

2022-08-02 15:50 UTC, Epicus7 commented on modules/hub/hub/blueprint.py
> +register_view(
В этом файле все register_view идут через одну строку друг от друга

// не критично

2022-08-02 15:50 UTC, Epicus7 commented on modules/hub/hub/views.py
> +        is_json = request.endpoint
Переменная не соответствует смыслу.

```suggestion
        is_json = (request.endpoint == "hub.admins_json")
```

2022-08-02 15:50 UTC, Epicus7 commented on modules/hub/hub/views.py
> +        server_admins = game_models[hub_current_server.id]["ErroAdmin"]
Здесь будет рантайм для Дракона, т.к. ты не добавил таблицу. Предлагаю в Hub.__get_actions добавлять новый Action только если для hub_current_server.id есть game_models[hub_current_server.id]["ErroAdmin"]

2022-08-02 15:50 UTC, Epicus7 commented on modules/hub/hub/views.py
> +    def get_admins():
```suggestion
    def get_admins_by_rank():
```

2022-08-02 15:50 UTC, Epicus7 commented on modules/hub/hub/views.py
> +        result = {rank:[admin.ckey for admin in admins if admin.rank == rank] for rank in [admin.rank for admin in admins]}
Страшно как-то ты написал это все. Тут мы сначала копируем список этих админов, потом еще бегаем по нему полностью для каждого ранга.

Можно сделать просто как-то так:

```
rank_to_admins = {}
for admin in server_admins.query.order_by(server_admins.rank).all():
    if admin.rank not in rank_to_admins:
        rank_to_admins[admin.rank] = []
    rank_to_admins[admin.rank] += admin.ckey
```

Не уверен насчет правильности синтаксиса, но такая логика и эффективнее в разы (всего один раз идем по списку и никаких лишних копирований), и гораздо более читабельно, чем твои генераторы.

2022-08-03 08:57 UTC, Zert0X commented on modules/hub/hub/views.py
> +        is_json = request.endpoint
а так можно было?

2022-08-03 10:50 UTC, Epicus7 approved these changes

2022-08-03 10:50 UTC, merged