added files upload/download
ChaoticOnyx/OnyxForum pull request #75
Opened 2022-07-27 11:26 UTC by Zert0X

![изображение](https://user-images.githubusercontent.com/42303535/181235775-2d09a17f-0f81-4547-bdae-aa561a944181.png)

2022-08-02 17:43 UTC, Epicus7 requested changes

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/app.py
> -
Лишнее изменение

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/forum/utils.py
> +    h = hashlib.sha1()
Странный выбор алгоритма. Обычно используют либо sha256, либо md5

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/forum/utils.py
> +    # make a hash object
Бесполезные комменты. Не надо писать в комментах что делает код - он должен быть понятным и без комментариев. Комменты нужны чтобы писать зачем код делает то, что делает, а не что он делает.

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/forum/utils.py
> +    # loop till the end of the file
Литерали такие комменты просто увеличивают когнитивную нагрузку для тех, кто пытается посмотреть код. Вместо того чтобы просто посмотреть код, мне приходится еще читать комменты и сравнивать совпадают ли они с тем, что делает код или нет)

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        if filename:
Проверка не нужна, можно пустое значение спокойно передавать в send_from_directory. Если что нам вернут 404, как нам и нужно

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/forum/views.py
> +            return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS
Расширение файла можно получить с помощью
[os.path.splitext](https://docs.python.org/3/library/os.path.html#os.path.splitext)

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        # check if the post request has the file part
Опять бесполезные комменты

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        def allowed_file(filename):
```suggestion
        def is_extension_allowed(filename):
```

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/forum/views.py
> +            path = os.path.join(current_app.config["UPLOAD_FOLDER"],current_user.discord)
Вместо **os.path.join** лучше всегда использовать **safe_join**, чтобы из-за каких-то других ошибок нельзя было выбраться из базовой директории и пойти гулять по хосту. Например, если получится как-то current_user-а спуфнуть и подменить current_user.discord на ../../../../ :)

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/forum/views.py
> +            return url_for("forum.upload_file")+"?file="+current_user.discord+"/"+filename
А так нельзя?
```suggestion
            return url_for("forum.upload_file", file=current_user.discord+"/"+filename)
```

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/forum/views.py
> +    def get(self):
Тут получается не Upload, а Download. Лучше сделать отдельный View, мне кажется.

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/forum/views.py
> +class UploadFile(MethodView):
Нужно ограничить доступ для зарегистрированных пользователей

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/templates/management/user_form.html
> +                                    <div class="author-avatar hidden-xs"><img src="" name="avatar" alt="avatar" width="150" max-height="150"></div>
Не надо проставить начальный src из form.avatar?

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/templates/management/user_form.html
> +                                <span id="error bad-file" style = "display: none;">We don’t support that file type.</span>
```suggestion
                                <span id="error bad-file" style = "display: none;">File type is not supported!</span>
```

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/templates/management/user_form.html
> +                                <span id="error failed-request" style = "display: none;">Something went really wrong, and we can’t process that file.</span>
```suggestion
                                <span id="error failed-request" style = "display: none;">Failed to process file</span>
```

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/templates/management/user_form.html
> +                                    <div class="author-avatar hidden-xs"><img src="" name="avatar" alt="avatar" width="150" max-height="150"></div>
А вижу ниже скрипт, тогда src вообще можно удалить, наверное

2022-08-02 17:43 UTC, Epicus7 commented on flaskbb/templates/user/change_user_details.html
> +            {% if form.avatar %}
Блин, копипаста лютая. Что тут, что с топиками. Обобщить бы как-то через макросы что ли...

2022-08-02 17:48 UTC, Zert0X commented on flaskbb/templates/user/change_user_details.html
> +            {% if form.avatar %}
тут два вызова на весь код, у тебя на форумы копипасты в разы больше

2022-08-02 17:48 UTC, No-Tips commented on flaskbb/forum/utils.py
> +    h = hashlib.sha1()
Давай md5, он быстрее. https://cryptopp.com/benchmarks.html

2022-08-02 17:49 UTC, Zert0X commented on flaskbb/forum/utils.py
> +    h = hashlib.sha1()
sha1 быстрее всех

2022-08-03 07:47 UTC, Zert0X commented on flaskbb/forum/views.py
> +            return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS
Энивей придётся удалять точку из результата ибо все экстеншены в конфигах указываются просто в виде
ALLOWED_EXTENSIONS = {'txt','png', 'jpg', 'jpeg', 'gif', 'pdf'}

2022-08-03 07:48 UTC, Zert0X commented on flaskbb/forum/views.py
> +            return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS
а так мы проверяем на наличие точки, и достаём крайнее расширение без точки

2022-08-03 07:49 UTC, Zert0X commented on flaskbb/forum/views.py
> +    def get(self):
можно просто file_manager ибо у тебя по факту в этом вью две функции загрузка и получение, а делать отдельный вью смысла нет ибо он энивей будет отсылаться  на эту ссылку

2022-08-03 11:00 UTC, Epicus7 commented on flaskbb/forum/utils.py
> +    h = hashlib.sha1()
Ладно, пофиг

2022-08-03 11:14 UTC, Epicus7 commented on flaskbb/forum/views.py
> +            return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS
`os.path.splitext(filename)[1][1:]` - даст тебе расширение файла без точки. `string[x:y]` - это, если что, называется slice. Оно дает тебе подмножество от x до y. Если x или y не указаны, то с начала/до конца соответственно.

Обычно, чтобы не тратить время, считается, что стандартные функции лучше, чем переизобретение велосипеда самостоятельно. Но раз это недостаточно убедительно, то давай потратим немного времени и разберемся на примере. Что твоя функция вернет для файла

`.bashrc` ?

Экстеншена у этого файла нет, точка обозначает что он invisible.

Алсо, еще как вариант, можно использовать

```
import pathlib
pathlib.Path(filename).suffix[1:]
```

2022-08-03 11:19 UTC, Epicus7 commented on flaskbb/templates/user/change_user_details.html
> +            {% if form.avatar %}
editor_filestatus копируется 4 раза
filestatus 2 раза

И они между собой еще очень похожи. Хотя бы span-ы с ошибками надо бы обобщить, ибо это пипец будет их потом менять. А лучше целиком editor_filestatus и filestatus вынести как макросы в отдельный файл

2022-08-03 11:19 UTC, Epicus7 commented on flaskbb/templates/user/change_user_details.html
> +            {% if form.avatar %}
editor_filestatus копируется 4 раза
filestatus 2 раза

И они между собой еще очень похожи. Хотя бы span-ы с ошибками надо бы обобщить, ибо это пипец будет их потом менять. А лучше целиком editor_filestatus и filestatus вынести как макросы в отдельный файл

2022-08-03 11:19 UTC, No-Tips commented on flaskbb/forum/views.py
> +            return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS
Слайсы же медленные, потому что это перебор массива, не?

2022-08-03 11:25 UTC, Epicus7 commented on flaskbb/forum/views.py
> +            return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS
Слайсы же медленные, потому что это перебор массива, не?

Хорошо что мы пишем веб-сервер, а не драйвера для Windows, тогда нас бы волновала скорость работы слайсов. А пока мы пишем веб-сервер скорость копирования строки фигня по сравнению со скоростью работы сети, которая в любом случае нас всегда ограничивает

2022-08-03 11:29 UTC, No-Tips commented on flaskbb/forum/views.py
> +            return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS
Ладно, справедливо, конечно, но скорость всегда лучше 😼

2022-08-03 11:31 UTC, Zert0X commented on flaskbb/templates/user/change_user_details.html
> +            {% if form.avatar %}
Вынес как макросы

2022-08-03 11:31 UTC, Zert0X commented on flaskbb/templates/user/change_user_details.html
> +            {% if form.avatar %}
flaskbb/templates/forum/editor_file_upload.html

2022-08-03 12:05 UTC, Epicus7 requested changes
Нужно сделать проверку на стороне бекенда на количество файлов от пользователя за день + проверку на размер файла поправить, а то это прям дыры.

Самый надежный вариант, что я вижу навскидку:

> 1. Сделать еще одну табличку в БД с аплоудами: id, datetime, ссылка, юзер
> 2. При каждом новом аплоуде проверять сколько юзер сегодня уже загрузил аплоудов. Если больше, скажем, 50, то посылать его нафиг. 
> 3. В форме отправки сообщения снизу писать оставшийся лимит загрузок на сегодня
> 4. При обновлении аватарки искать старую в БД и сносить её, если она там есть (если она не из интернета, а у нас загружена)
> 
> Опционально:
> 1. Сделать лимит - опцией группы юзера, чтобы можно было разным группам настраивать разный лимит.

Может попроще что-то сделать пока можно, хз

2022-08-08 17:55 UTC, No-Tips reviewed
Надо тестить на проде

2022-08-08 17:55 UTC, No-Tips commented on flaskbb/configs/config.cfg.template
> +USER_UPLOAD_FOLDER_LIMIT = 500*1024*1024
А почему нельзя просто написать размер?

2022-08-08 17:55 UTC, No-Tips commented on flaskbb/forum/utils.py
> +import hashlib
мб лучше 
```suggestion
from hashlib import sha1
```

2022-08-08 17:55 UTC, No-Tips commented on flaskbb/forum/views.py
> +    user_groups_file_max_length.append(current_app.config["MAX_UPLOAD_SIZE"])
По4 тут называется переменные с длинной файла, а сравниваешь ты с размером... Как по мне длинна файла это хз, его название, но не размер.

2022-08-08 17:55 UTC, No-Tips commented on flaskbb/forum/views.py
> +            file.save(safe_join(path,filename))
Тут равзе нужен второй сейф_джоин? path уже отсанитайзен выше

2022-08-08 17:55 UTC, No-Tips commented on flaskbb/forum/views.py
> +            upload_file.save()
Втф че я не понял, ты что сохраняешь два файла?

2022-08-08 17:55 UTC, No-Tips commented on flaskbb/themes/onyx/src/js/file_upload.js
> +        formData.append('file', file);
Не хочешь аппенд вынести за ифелс?

2022-08-08 17:55 UTC, No-Tips commented on flaskbb/themes/onyx/src/scss/_karma.scss
> +    margin-bottom: 0.2em;
Что в этом пре забыл ксс кармы...

2022-08-08 23:13 UTC, Doster-d reviewed
Я устал

2022-08-08 23:13 UTC, Doster-d commented on flaskbb/forum/models.py
> +        return self
```suggestion
        return self

```

2022-08-08 23:13 UTC, Doster-d commented on flaskbb/forum/utils.py
> +import hashlib
+

2022-08-08 23:13 UTC, Doster-d commented on flaskbb/forum/utils.py
> +    h = hashlib.sha1()
```suggestion
    h = sha1()
```

2022-08-08 23:13 UTC, Doster-d commented on flaskbb/forum/views.py
> +    user_groups_file_max_length=[current_user.primary_group.uploaded_file_max_length]
```suggestion
    user_groups_file_max_length = current_user.primary_group.uploaded_file_max_length
    if user_groups_file_max_length == -1:
        return -1
```
Зачем так сложно считать, память не резиновая.
И еще этот -1 мех

2022-08-08 23:13 UTC, Doster-d commented on flaskbb/forum/views.py
> +        user_groups_file_max_length.append(group.uploaded_file_max_length, )
```suggestion
        if -1 == group.uploaded_file_max_length:
            return -1
        user_groups_file_max_length = max(group.uploaded_file_max_length, user_groups_file_max_length)
```

2022-08-08 23:13 UTC, Doster-d commented on flaskbb/forum/views.py
> +    if -1 in user_groups_file_max_length:
```suggestion
    if -1 == user_groups_file_max_length:
```

2022-08-08 23:13 UTC, Doster-d commented on flaskbb/forum/views.py
> +        return max(user_groups_file_max_length)
```suggestion
        return user_groups_file_max_length
```

2022-08-08 23:13 UTC, Doster-d commented on flaskbb/forum/views.py
> +    user_groups_file_max_length.append(current_app.config["MAX_UPLOAD_SIZE"])
```suggestion
    user_groups_file_max_length = max(current_app.config["MAX_UPLOAD_SIZE"], user_groups_file_max_length )
```

2022-08-08 23:13 UTC, Doster-d commented on flaskbb/forum/views.py
> +    user_groups_upload_folder_limit=[current_user.primary_group.upload_folder_limit]
```suggestion
    user_groups_upload_folder_limit = current_user.primary_group.upload_folder_limit
```
Сразу видно человека, что не решал 27 задание ОГЭ по информатики...

2022-08-08 23:13 UTC, Doster-d commented on flaskbb/forum/views.py
> +        user_groups_upload_folder_limit.append(group.upload_folder_limit, )
```suggestion
        user_groups_upload_folder_limit = max(group.upload_folder_limit, user_groups_upload_folder_limit)
```

2022-08-08 23:13 UTC, Doster-d commented on flaskbb/forum/views.py
> +    user_groups_upload_folder_limit.append(current_app.config["USER_UPLOAD_FOLDER_LIMIT"])
```suggestion
    user_groups_upload_folder_limit = max(user_groups_upload_folder_limit, current_app.config["USER_UPLOAD_FOLDER_LIMIT"])
```

2022-08-08 23:13 UTC, Doster-d commented on flaskbb/forum/views.py
> +    return max(user_groups_upload_folder_limit)
```suggestion
    return user_groups_upload_folder_limit
```

2022-08-09 06:47 UTC, Zert0X commented on flaskbb/forum/views.py
> +    user_groups_file_max_length.append(current_app.config["MAX_UPLOAD_SIZE"])
Потому что размер файла и есть его длина лол

2022-08-09 06:48 UTC, Zert0X commented on flaskbb/forum/views.py
> +    return max(user_groups_upload_folder_limit)
Достер кто тебя учил на 5 строк кода высирать отдельные ЧРы? Я нихера не пойму как их склеить между собой

2022-08-09 06:52 UTC, Zert0X commented on flaskbb/configs/config.cfg.template
> +USER_UPLOAD_FOLDER_LIMIT = 500*1024*1024
Никто не запрещает, можешь писать в байтах размер сразу, просто так удобнее видеть что это 5Мбайт и 500Мбайт соответственно

2022-08-09 06:53 UTC, Zert0X commented on flaskbb/forum/views.py
> +    user_groups_file_max_length=[current_user.primary_group.uploaded_file_max_length]
С -1 согласен, но брух у питухона не дефайнов

2022-08-09 07:23 UTC, Zert0X commented on flaskbb/themes/onyx/src/scss/_karma.scss
> +    margin-bottom: 0.2em;
там небольшая правка бага с аватарками, имею право аватарки я трогал тут же

2022-08-09 12:50 UTC, Doster-d commented on flaskbb/forum/views.py
> +    return max(user_groups_upload_folder_limit)
У меня шифт не работает! Нормально не могу выделить

2022-08-09 13:34 UTC, Zert0X commented on flaskbb/forum/views.py
> +    return max(user_groups_upload_folder_limit)
Так лкм зажми и тяни

2022-09-07 20:04 UTC, Epicus7 commented on flaskbb/configs/config.cfg.template
> +USER_UPLOAD_FOLDER_LIMIT = 500*1024*1024
Можно было сделать лимит в мегабайтах просто, нафига он с точностью до байт нужен? И комментарии - зло, лучше было бы указать размерность в названии переменной

// не критично

2022-09-07 20:05 UTC, Epicus7 commented on flaskbb/forum/views.py
> +    user_groups_file_max_length.append(current_app.config["MAX_UPLOAD_SIZE"])
Согласен с НоТипсом, терминология такая себе. Все-таки у файлов размеры, а не длина

// не критично

2022-09-07 20:08 UTC, Epicus7 commented on flaskbb/forum/views.py
> +            file.save(safe_join(path,filename))
Джойнить всегда лучше с помощью safe_join. Мало ли откуда filename возьмется? Оверхеда тут нет критичного

2022-09-07 20:10 UTC, Epicus7 commented on flaskbb/forum/views.py
> +            upload_file.save()
file - это файл, а upload_file - это объект-запись в БД.

Но да, название переменных фиговое, из-за чего непонятно сходу что есть что

// не критично

2022-09-07 21:21 UTC, Epicus7 requested changes
Весь бекенд посмотрел, JS надо бы отдельно еще посмотреть

2022-09-07 21:21 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        size+=file_length
Лучше вынести в отдельную функцию get_folder_size. И мб сразу сделать её рекурсивной, на случай вложенных директорий. Только еще нужна тогда проверка на . и .., чтобы не убежать всю ОС считать

2022-09-07 21:21 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        if file and is_extension_allowed(file.filename):
Выше уже проверяли extension. И что могло случится с file? Зачем на него проверять?

2022-09-07 21:21 UTC, Epicus7 commented on flaskbb/forum/views.py
> +            file.seek(0)
Это уже второй file.seek(0). Наверное один можно убрать

2022-09-07 21:21 UTC, Epicus7 commented on flaskbb/forum/views.py
> +            upload_file.save()
Посмотрел еще раз код. Лучше переименовать переменные конечно:
file -> received_file_object
upload_file -> uploaded_file_record

2022-09-07 21:21 UTC, Epicus7 commented on flaskbb/forum/views.py
> +def user_get_file_max_length():
user_get_file_max_length и user_get_upload_folder_limit очень похожи друг на друга. Можно, мне кажется, объединить в одну функцию:

```
@attr.s
class UploadLimits:
    file_size = attr.ib()
    folder_size = attr.ib()

def get_user_upload_limits() -> UploadLimits:
```

2022-09-07 21:21 UTC, Epicus7 commented on flaskbb/forum/views.py
> +    for group in current_user.secondary_groups:
Можно сделать просто вот такой цикл, сразу со всеми группами:

```suggestion
    for group in [*current_user.secondary_groups, current_user.primary_group]:
```
Тогда код сильно упростится, основную группу не придется отдельно рассматривать

2022-09-07 21:21 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        return -1
Эти -1 смущают. Зачем нам в БД вообще хранить -1, если в БД поддерживается NULL? По дефолту в БД должны быть пустые поля. Тут соответственно проверять на None надо

2022-09-07 21:21 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        user_groups_file_max_length = current_app.config["MAX_UPLOAD_SIZE"]
Дефолтовое значение надо брать, если во всех группах соответственно None в БД прописан.

2022-09-07 21:21 UTC, Epicus7 commented on flaskbb/management/forms.py
> +        default=0,
Зачем тут default? Лучше оставить по дефолту пустым, мне кажется

2022-09-07 21:21 UTC, Epicus7 commented on flaskbb/templates/management/user_form.html
> +                            <span class="btn btn-warning" id="upload-button" onclick="UploadAvatar('{{url_for('forum.upload_file')}}','{{ csrf_token() }}')">Upload</span>
Надо бы добавить {% trans %}{% endtrans %}

2022-09-18 13:11 UTC, Zert0X commented on flaskbb/forum/models.py
> +            self.original_name = "file"
Прикол в другом, мы отдаём файл с этим неймом и как бы нейм файла вроде не может быть пустым от слова совсем, выходит что получится ошибка

2022-09-18 13:42 UTC, Zert0X commented on flaskbb/forum/views.py
> +        return -1
Тут отдельный вопрос ибо делалось это как бан группа, и если поставить группе "-1" и выставить группу юзеру, то юзер не сможет загружать файлы.

2022-09-18 13:44 UTC, Zert0X commented on flaskbb/forum/views.py
> +        user_groups_file_max_length = current_app.config["MAX_UPLOAD_SIZE"]
Питон не умеет сравнивать None и int, как по мне лишний гемор с проверкой на нон.

2022-09-18 13:48 UTC, Zert0X commented on flaskbb/forum/views.py
> +        size+=file_length
Две строчки выносить в отдельную функцию? Плюс мы же вроде не планировали рекурсивные директории

2022-09-18 13:48 UTC, Zert0X commented on flaskbb/forum/views.py
> +        size+=file_length
Да и вложенные директории не предусмотрены в целом

2022-09-18 13:51 UTC, Zert0X commented on flaskbb/forum/views.py
> +        if file and is_extension_allowed(file.filename):
Где? Там не проверка там дефайн чтобы эта проверка не была громадной

2022-09-18 13:53 UTC, Zert0X commented on flaskbb/forum/views.py
> +            file.seek(0)
В том то и прикол что нет, после каждой операции с файлом надо его переносить на 0, или иначе оставляем курсор в конце файла

2022-09-18 14:00 UTC, Zert0X commented on flaskbb/management/forms.py
> +        default=0,
Тогда будет None, а у питона трудность сравнения None и Int

2022-09-18 14:02 UTC, Zert0X commented on flaskbb/user/models.py
> +    upload_folder_limit = db.Column(db.Integer, default=0, nullable=False)
upload_size_limit - тут согласен
А фолдер я бы оставил

2022-09-18 15:21 UTC, Epicus7 commented on flaskbb/user/models.py
> +    upload_folder_limit = db.Column(db.Integer, default=0, nullable=False)
Мне не нравится что folder - это конкретно твоя реализация. Ты мог бы, например, хранить все файлы в одной папке и просто сопоставлять их с юзерами через БД. Или наоборот у пользователя могло бы быть много папок. Зачем выносить в интерфейс особенности реализации (знание о существовании некой папки)?

2022-09-18 15:22 UTC, Epicus7 commented on flaskbb/forum/models.py
> +            self.original_name = "file"
Тогда ассерт лучше поставить на название файла

2022-09-18 15:27 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        size+=file_length
Ну тут типичная проблема с абстракциями. Мы тут занимаемся обработкой POST запроса, но внезапно проваливаемся на пару уровней абстракции вниз и начинаем чот делать через os.scandir. Это разные уровни абстракции и такой код сложнее читать. Когда пытаешься понять что делает обработчик запроса тупо спотыкаешься об эти os.scandir и прочее. Поэтому считается что такие куски кода надо выносить в отдельные функции и давать им осмысленное название, чтобы код более высокого уровня абстракции мог просто вызвать её, и разрабочик, который будет читать этот код, мог даже не разбираться как именно ты считаешь размер директории.

Вот тебе ссылка на авторитетный источник, где можно поподробнее почитать почему такой код лучше не писать :)
https://habr.com/ru/company/lanit/blog/516352/#:~:text=%D0%A1%D0%BE%D0%B3%D0%BB%D0%B0%D1%81%D0%BD%D0%BE%20%C2%AB%D0%A7%D0%B8%D1%81%D1%82%D0%BE%D0%BC%D1%83%20%D0%BA%D0%BE%D0%B4%D1%83%C2%BB%2C%20%D0%B5%D1%81%D0%BB%D0%B8%20%D0%BC%D1%8B%20%D1%85%D0%BE%D1%82%D0%B8%D0%BC%20%D1%83%D0%B1%D0%B5%D0%B4%D0%B8%D1%82%D1%8C%D1%81%D1%8F%2C%20%D1%87%D1%82%D0%BE%20%D0%BD%D0%B0%D1%88%D0%B8%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D1%8F%D1%8E%D1%82%20%D1%82%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE%20%D0%BE%D0%B4%D0%BD%D1%83%20%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D1%83%2C%20%D0%BD%D0%B0%D0%BC%20%D0%BD%D1%83%D0%B6%D0%BD%D0%BE%20%D1%83%D0%B1%D0%B5%D0%B4%D0%B8%D1%82%D1%8C%D1%81%D1%8F%2C%20%D1%87%D1%82%D0%BE%20%D0%B2%D1%81%D0%B5%20%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%8B%20%D0%B2%20%D0%BA%D0%B0%D0%B6%D0%B4%D0%BE%D0%B9%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D1%8F%D1%82%D1%81%D1%8F%20%D0%BD%D0%B0%20%D0%BE%D0%B4%D0%BD%D0%BE%D0%BC%20%D1%83%D1%80%D0%BE%D0%B2%D0%BD%D0%B5%20%D0%B0%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%86%D0%B8%D0%B8.

2022-09-18 15:32 UTC, Zert0X commented on flaskbb/user/models.py
> +    upload_folder_limit = db.Column(db.Integer, default=0, nullable=False)
Уговорил переименую

2022-09-18 15:33 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        size+=file_length
Блин, ссылка на выделенный текст не работает. Ну там короче часть 4 про этот случай как раз

2022-09-18 15:33 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        if file and is_extension_allowed(file.filename):
А реально, может поближе тогда перенести?

2022-09-18 15:33 UTC, Epicus7 commented on flaskbb/forum/views.py
> +            file.seek(0)
Да, я понимаю зачем ты напихал seek-ов. Хз почему я так написал.

Наверное, seek стоит убрать в hash_file во внутрь. Операция же последняя там происходит?

2022-09-18 15:33 UTC, Epicus7 commented on flaskbb/management/forms.py
> +        default=0,
А как тогда отличать дефолтное поведение и если кто-то захотел поставить в настройках группе этот размер в 0?

2022-09-18 15:34 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        return -1
Обсудили в дискорде это

2022-09-18 15:35 UTC, Zert0X commented on flaskbb/management/forms.py
> +        default=0,
> А как тогда отличать дефолтное поведение и если кто-то захотел поставить в настройках группе этот размер в 0?

Так дефолтное поведение и есть 0

2022-09-18 15:35 UTC, Zert0X commented on flaskbb/management/forms.py
> +        default=0,
или я не совсем пойму вопроса

2022-09-18 15:36 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        user_groups_file_max_length = current_app.config["MAX_UPLOAD_SIZE"]
А если кто-то в настройках начнет ставить группам размер 0?

2022-09-18 19:51 UTC, Epicus7 commented on flaskbb/management/forms.py
> +        default=0,
Обсудили в дискорде

2022-09-18 20:10 UTC, Epicus7 requested changes

2022-09-18 20:10 UTC, Epicus7 commented on flaskbb/user/views.py
> +        if not (file_owner.user_id == current_user.id or self.get_permissions()['admin']):
```suggestion
        if not (file_owner.user_id == current_user.id or has_permission(current_user, "admin"):
```
Без понятия что такое **self**.get_permissions и откуда оно берет юзера. Мой вариант мне кажется более явный

2022-09-18 20:10 UTC, Epicus7 commented on flaskbb/user/views.py
> +        if not (file_owner.user_id == current_user.id or self.get_permissions()['admin']):
Только надо еще импортировать has_permission, да

2022-09-18 20:10 UTC, Epicus7 commented on flaskbb/user/views.py
> +            logger.warn("File {}(owned by:{}) was tried to be deleted by {}(discord:{})".format(file_record, file_owner, current_user.username, current_user.discord))
Так а return где? Мы же дальше пойдем и файл удалим все равно

2022-09-18 20:10 UTC, Epicus7 commented on flaskbb/user/views.py
> +            logger.warn("File {}(owned by:{}) was tried to be deleted by {}(discord:{})".format(file_record, file_owner, current_user.username, current_user.discord))
И owner-у тоже дискорд, наверное, надо написать тогда, а то по никнейму потом хрен найдешь

2022-09-18 20:10 UTC, Epicus7 commented on flaskbb/forum/views.py
> +        received_file_object.seek(0)
Все еще не вынес в отдельную функцию

2022-09-18 20:10 UTC, Epicus7 commented on flaskbb/forum/views.py
> +            return '.' in filename and os.path.splitext(filename)[1][1:] in ALLOWED_EXTENSIONS
Я предлагал эту функцию перенести поближе к использованию

2022-09-19 11:32 UTC, Zert0X commented on flaskbb/forum/views.py
> +        size+=file_length
Вынес

2022-09-19 12:17 UTC, Epicus7 requested changes
Теперь все норм, единственное, забыл что надо изменения темы еще скопировать в Onyx Light

2022-09-19 16:18 UTC, Epicus7 approved these changes

2022-09-19 16:21 UTC, merged