Community rating
ChaoticOnyx/OnyxForum pull request #76
Opened 2022-08-19 14:16 UTC by Zert0X

Раз в неделю каждому юзеру обновляется рейтинг сообщества*
Вывод рейтинга сообщества:
<details>
<summary>В Профиле</summary>
![изображение](https://user-images.githubusercontent.com/42303535/185637888-33f2e2dc-061f-4602-b5ab-1f2cd086a111.png)
</details>

<details>
<summary>В форуме</summary>
![изображение](https://user-images.githubusercontent.com/42303535/185637893-4e44b783-aa07-4e20-bcb7-b5d94257a07a.png)
</details>

*Отсчёт начинается заново с каждого перезапуска форума

2022-08-21 16:58 UTC, No-Tips commented on modules/hub/hub/features/community_rating/render.py
> +            community_rating_color += "5"
Что за меджик намберс

2022-08-21 16:58 UTC, No-Tips commented on modules/hub/hub/features/community_rating/community_rating.py
> +    assert value
Я не уверен, что тут нужны ассерты, проверка на них у тебя есть выше в функциях...

2022-08-21 16:58 UTC, No-Tips commented on modules/hub/hub/features/community_rating/render.py
> +            community_rating_color += "5"
О нет, я посмотрел на ксс, и мне стало плохо...

2022-08-21 16:59 UTC, No-Tips commented
Ловла ты что употреблял, когда делал ксс для рейтинга?

2022-08-21 16:59 UTC, Zert0X commented on modules/hub/hub/features/community_rating/community_rating.py
> +    assert value
Логи можно вызывать отдельно от функций пусть будет

2022-08-21 17:00 UTC, Zert0X commented on modules/hub/hub/features/community_rating/render.py
> +            community_rating_color += "5"
Страдай, в идеале конечно просто передавать переменную в css но мне и эпикусу лень

2022-08-26 23:18 UTC, Epicus7 requested changes

2022-08-26 23:18 UTC, Epicus7 commented on modules/hub/hub/features/community_rating/community_rating.py
> +def get_user_community_rating(user):
Эта функция будет вызываться очень часто (при отрисовке каждой страницы форума по разу на каждый пост). Нам нужно её максимально ускорить, иначе форум начнет умирать, когда лайков постов станет слишком много.

Предлагаю все-таки записывать в БД community_rating вообще ВСЕ изменения рейтинга, в том числе лайки постов. Тогда здесь можно будет делать SQL запрос на сумму столбца в одной таблице с фильтрацией по игроку, БД будет этот запрос считать один раз и кэшировать внутри себя, что позволит нам сильно сэкономить.

Для этого нужно:
1. Когда лайкают пост, создавать еще запись в community_rating. В таблицу post_rate добавить столбец со ссылкой на соответствующую запись в community_rating
2. Когда реакцию под постом удаляют, сносить запись в community_rating, на которую ссылается соответствующая запись в post_rate

Тогда здесь мы сможем просто суммировать все столбцы в community_rating для конкретного игрока

2022-08-26 23:18 UTC, Epicus7 commented on modules/hub/hub/features/community_rating/community_rating.py
> +    app = create_app(config='flaskbb.cfg')
У нас тут создается второй форум целый? Фигня какая-то, надо получить текущее приложение, которое уже создано, а не новое создавать. Где-то уже есть код, который получает существующее приложение. В обработчиках ивентов дискорда, кажется, что-то такое есть. Посмотреть надо

2022-08-26 23:18 UTC, Epicus7 commented on modules/hub/hub/features/community_rating/community_rating.py
> +            if get_user_community_rating(user) >=0:
У user-а рейтинг не должен переходить через ноль. Если 0, то меняться не должен. Если +-1, то становится 0. У тебя сейчас не так

2022-08-26 23:18 UTC, Epicus7 commented on modules/hub/hub/features/community_rating/__init__.py
> +from apscheduler.schedulers.background import BackgroundScheduler
Надо, наверное, apscheduler добавить в зависимости

2022-08-27 16:16 UTC, Zert0X commented on modules/hub/hub/features/community_rating/community_rating.py
> +def get_user_community_rating(user):
Предлагаю в целом каждый раз не считать вонючий рейтинг у пользователя, а просто его дополнительно хранить конкретно в БД пользователей

2022-09-07 19:54 UTC, Epicus7 commented on modules/hub/hub/features/community_rating/community_rating.py
> +def get_user_community_rating(user):
Не, это плохой вариант, так как синхронизация - лишняя головная боль. Я пробовал раньше так делать с суммой опиксов игрока. Одна ошибка в коде и у тебя десинхрон, который надо идти руками в БД править

Да и профита ноль, т.к. сумма должна кэшироваться в БД и так, так что тут оптимизации не будет никакой

2022-09-20 09:09 UTC, Zert0X commented on modules/hub/hub/features/community_rating/community_rating.py
> +def get_user_community_rating(user):
done, вроде сделал как ты хотел

2022-09-20 09:09 UTC, Zert0X commented on modules/hub/hub/features/community_rating/community_rating.py
> +    app = create_app(config='flaskbb.cfg')
done

2022-09-20 09:09 UTC, Zert0X commented on modules/hub/hub/features/community_rating/community_rating.py
> +            if get_user_community_rating(user) >=0:
done

2022-09-20 09:09 UTC, Zert0X commented on modules/hub/hub/features/community_rating/__init__.py
> +from apscheduler.schedulers.background import BackgroundScheduler
done

2022-09-20 10:40 UTC, Epicus7 requested changes

2022-09-20 10:40 UTC, Epicus7 commented on modules/hub/hub/features/karma/views.py
> +                        dislikes[user]=users[user]
```suggestion
                for user, change in users:
                    if change>0:
                        likes[user]=change
                    else:
                        dislikes[user]=change
```

А то тут какой-то c-style у тебя)

2022-09-20 10:40 UTC, Epicus7 commented on modules/hub/hub/features/karma/views.py
> +                return 'No one don\'t rate this post yet!'
```suggestion
                return 'The post isn't rated yet'
```

2022-09-20 10:40 UTC, Epicus7 commented on modules/hub/hub/features/karma/post_rating.py
> +    return users_and_change
А почему просто не вернуть список PostRate, которые относятся к посту? Тогда вызывающий код сможет прямо использовать post_rate.user и post_rate.change. И не надо тут бегать по циклу будет и какие-то словари новые создавать.

И название функции можно будет более понятным сделать: "get_all_post_rates_by_post", по аналогии с "get_all_post_rates_by_user" выше (еще и перенести можно к ней, раз они такие похожие станут).

2022-09-20 10:40 UTC, Epicus7 commented on modules/hub/hub/features/karma/post_rating.py
> +    return summary
А это где используется? Не вижу использований

2022-09-20 10:40 UTC, Epicus7 commented on modules/hub/hub/features/community_rating/models.py
> +from flaskbb.extensions import db, db_hub
db_hub тут не нужен

2022-09-20 10:40 UTC, Epicus7 commented on modules/hub/hub/features/community_rating/community_rating.py
> +    return summary
Нет, не так. Надо использовать встроенный в SQL summary. Как-то так:

```suggestion
   cursor: db_hub.Query = db_hub.session.query(0 + func.sum(CommunityRating.change))\
        .filter(CommunityRating.user_id == user.id)
    return cursor.first()[0] or 0
```
Оно будет кэшироваться внутри БД и нам не придется каждый раз пересчитывать

2022-09-20 10:40 UTC, Epicus7 commented on modules/hub/hub/features/community_rating/community_rating.py
> +@scheduler.task('interval', id='weekly_community_rating_updatge', weeks=1)
```suggestion
@scheduler.task('interval', id='weekly_community_rating_update', weeks=1)
```

2022-09-20 10:40 UTC, Epicus7 commented on modules/hub/hub/features/community_rating/community_rating.py
> +                    change_user_community_rating(user, 2)
Чо с кодстайлом случилось? :D

Скобочки вообще лишние. 54 и 56 строки уехали. Вокруг арифметических знаков и знаков сравнения должны быть пробелы.

А еще можно применить немного логики и упростить это нагромождение ифов :) :
```suggestion
            if not user_community_rating:
                return
            change_user_community_rating(user, copysign(min(2, abs(user_community_rating)), user_community_rating))
```

2022-09-20 10:40 UTC, Epicus7 commented on flaskbb/themes/onyx_light/src/js/post_rating.js
> +        type: "POST",
Вот, Users можно убрать нафиг, а запрос поменять на GET. Тогда в обработчике PostRateView обрабатывать это не в Post, а в Get

2022-09-20 10:45 UTC, Zert0X commented on modules/hub/hub/features/community_rating/render.py
> +def render_community_rating(user):
Я кстати хз куда скушались отступы вроде добавлял

2022-09-20 11:42 UTC, Zert0X commented on flaskbb/themes/onyx/static/css/styles.css
>   *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,
Откатил гитигнор, зальём этот с css и js

2022-09-20 11:42 UTC, Zert0X commented on .gitignore
> +flaskbb/themes/onyx_light/static/css/styles.css
Откатил

2022-09-20 11:43 UTC, Zert0X commented on modules/hub/hub/features/community_rating/render.py
> +def render_community_rating(user):
Done

2022-09-20 11:43 UTC, Zert0X commented on modules/hub/hub/features/karma/post_rating.py
> +    community_rating_record.save()
Done

2022-09-20 11:43 UTC, Zert0X commented on modules/hub/hub/features/karma/views.py
> +        if "Users" in request.form:
Done

2022-09-20 11:43 UTC, Zert0X commented on modules/hub/hub/features/karma/views.py
> +                        dislikes[user]=users[user]
Done

2022-09-20 11:47 UTC, Zert0X commented on modules/hub/hub/features/karma/views.py
> +                return 'No one don\'t rate this post yet!'
Убрано из-за немного другой системы, будет просто пустой список лайков/дизлайков

2022-09-20 11:47 UTC, Zert0X commented on modules/hub/hub/features/karma/post_rating.py
> +    return users_and_change
Done

2022-09-20 11:47 UTC, Zert0X commented on modules/hub/hub/features/karma/post_rating.py
> +    return summary
Легаси с прошлой реализации, убрано.

2022-09-20 11:47 UTC, Zert0X commented on modules/hub/hub/features/community_rating/models.py
> +from flaskbb.extensions import db, db_hub
Done

2022-09-20 12:45 UTC, Epicus7 approved these changes

2022-09-20 12:46 UTC, merged